print ("what is your name?")
nameUser = input()
print("How old are you?")
ageUser = input()
print("Where are you live?")
cityUser = input()
print("This is {0}".format(nameUser))
print("It is {0}".format(ageUser))
print("s(he) lives in {0}".format(cityUser))
